version: '3.9'

services:
    postgres:
        container_name: postgres-dice-betting
        image: postgres:15.4
        ports:
            - '${POSTGRES_PORT}:5432'
        user: ${POSTGRES_USERNAME}
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USERNAME}
            - POSTGRES_DB=${POSTGRES_DATABASE_NAME}
